name: ger_ton_argent
description: Personal finance manager for Côte d'Ivoire (Flutter + Firebase + Hive)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.2
  firebase_ai: ^0.1.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI/Charts
  fl_chart: ^0.68.0

  # Utils
  uuid: ^4.4.0
  flutter_local_notifications: ^17.2.2
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  
  # Image handling
  image_picker: ^1.0.7
  firebase_storage: ^12.1.0
  
  # Localization
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/translations/

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo.png"
  web: false
  android: true
  ios: true
  windows: false
  linux: false
  macos: false
