// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project credentials

  static const FirebaseOptions web = FirebaseOptions(
    
    appId: '1:1067663277279:web:61d7a3e18a61580f20bd6a',
    messagingSenderId: '1067663277279',
    projectId: 'gertonargent-app',
    authDomain: 'gertonargent-app.firebaseapp.com',
    storageBucket: 'gertonargent-app.firebasestorage.app',
    measurementId: 'G-87QMZD9BSX',
  );

  // Run 'flutterfire configure' to generate these automatically

  static const FirebaseOptions android = FirebaseOptions(
    
    appId: '1:1067663277279:android:3392e26eb31ccb1520bd6a',
    messagingSenderId: '1067663277279',
    projectId: 'gertonargent-app',
    storageBucket: 'gertonargent-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
  
    appId: '1:1067663277279:ios:aa6173e87a15c36020bd6a',
    messagingSenderId: '1067663277279',
    projectId: 'gertonargent-app',
    storageBucket: 'gertonargent-app.firebasestorage.app',
    iosBundleId: 'com.example.gerTonArgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'gertonargent',
    storageBucket: 'gertonargent.appspot.com',
    iosBundleId: 'com.example.gerTonArgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
   
    appId: '1:1067663277279:web:a84932d798f218b320bd6a',
    messagingSenderId: '1067663277279',
    projectId: 'gertonargent-app',
    authDomain: 'gertonargent-app.firebaseapp.com',
    storageBucket: 'gertonargent-app.firebasestorage.app',
    measurementId: 'G-QZB5266348',
  );

}